server:
  port: 8082

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  pattern:
    console: "%5p | %-40.40logger{39} : %m%n"
  level:
    org:
      springframework:
        web: DEBUG